icd_code_list: 'icd_outcome_codes.txt'
icd_date_matrices: 
  4dig: 'Date_Matrices/4digit_thresh15_053122.final.RR.condition_matrix.csv.gz'
  3dig: 'Date_Matrices/3digit_thresh15_053122.final.RR.condition_matrix.csv.gz'
  4dig_I10check: 'Date_Matrices/4digit_thresh15_053122.final.RR.I10_check.condition_matrix.csv.gz'

phecode_list: 'phecode_outcome_codes.txt'
phecode_date_matrices: 
  4dig_to_phe: 'Date_Matrices/phecode.4digit_thresh15_053122.final.RR.condition_matrix.csv.gz'
  4dig_to_phe_I10check: 'Date_Matrices/phecode.4digit_thresh15_053122.final.RR.I10_check.condition_matrix.csv.gz'

icd_index_code_list: ['I10', 'E11.9']
phecode_index_code_list: ['250.2']

demographics_file: '/project/ritchie02/projects/Disease_Cooccurence/Penn_EHR_Data/HTN_COHORT_DEMOGRAPHICS.csv'
icd_map_file: '/project/ritchie08/personal/pankhuri_lpc/DETECT/dissertation_analysis/ICD10_CMS.txt'